image: gradle:4.6.0-jdk8-alpine

before_script:
  - echo "----- Start CI -----"
  - pwd
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - checkstyle
  - build
  - test
  - coverage
  - javadoc
  - staging
  - deploy

checkstyle:
  stage: checkstyle
  script:
    - gradle -q check
  tags:
    - cs108
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/checktyle/
  only:
    - /^rl-.*$/

test:
  stage: test
  script:
    - gradle -q test
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/test/

coverage:
  stage: coverage
  script:
    - gradle -q jacocoTestReport
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/reports/coverage/
  
build:
  stage: build
  script:
    - gradle -q build
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/libs/*.jar
      - app/out/

javadoc:
  stage: javadoc
  script:
    - gradle -q javadoc
  tags:
    - cs108
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - docs/javadocs/

staging:
  stage: staging
  script:
    - echo "Missing sh script to setup testing/staging environment."
  when: manual
  only:
    - /^rl-.*$/
    - dev

deploy:
  stage: staging
  script:
    - echo "Missing sh script to setup deployment environment."
  when: manual
  only:
    - master

after_script:
  - echo "----- End CI -----"
