image: java:8-jdk

stages:
  - test
  - build
 
before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  script:
    - gradlew test
  tags:
  - cs108

build:
  stage: build
  script:
  - gradlew build
  tags:
  - cs108

after_script:
  - echo "End CI"