image: subluminalthegame/gradle:4.6.0-jdk8-openjfx-alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_OPTS="-Dfile.encoding=utf-8"

cache:
  paths:
    - .gradle/

stages:
  - build
  - test
  - docker
  - deploy

checkstyle:
  stage: test
  script:
    - gradle check -x test
  tags:
    - cs108-dind
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    expire_in: 2 hours
    paths:
     - app/build/reports/checkstyle/
  only:
    - /^rl-.*$/

build:
  stage: build
  script:
    - gradle clean
    - gradle build -x check -x test -x javadoc -x sourcesjar -x javadocjar -x distZip -x distTar
  tags:
    - cs108-dind
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    expire_in: 2 hours
    paths:
      - app/build/libs/

test:
  stage: test
  script:
    - gradle test
  tags:
    - cs108-dind
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    expire_in: 2 hours
    paths:
      - app/build/reports/
      - app/build/test-results/
      - app/build/jacoco/

coverage:
  stage: test
  script:
    - gradle test jacocoTestReport
    - cat app/build/reports/coverage/index.html
    - "echo -n \"Coverage: \" && grep -Eo \"Total.*?([0–9]{1,3})%\" app/build/reports/coverage/index.html | sed \"s/%.*/%/;s/.*>//g;\""
  coverage: '/Coverage: \d+\%/'
  tags:
    - cs108-dind
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    expire_in: 2 hours
    paths:
      - app/build/reports/coverage/

javadoc:
  stage: test
  script:
    - gradle javadoc
    - gradle javadoccoverage
  tags:
    - cs108-dind
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    expire_in: 2 hours
    paths:
      - docs/javadoc/
  only:
    - master
    - /^rl-.*$/
    - ft-buildtools-luc

build-image:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_DRIVER: 'overlay2'
    VERSION: 'null'
  services:
  - docker:dind
  script:
  - TAG=$(cat ./VERSION)
  - DEPLOYHOST=164.132.199.58
  - echo "Building and pushing server version $TAG to https://hub.docker.com."
  - docker build -t subluminalthegame/subluminal:latest -t subluminalthegame/subluminal-server:$(echo $TAG) --file ./docker/dockerfile-subluminal.yml --build-arg VERSION=$(echo $TAG) --build-arg PORT=1729 .
  - docker login -u subluminalthegame -p $DOCKERHUB_PASSWORD
  - docker push subluminalthegame/subluminal-server
  tags:
    - cs108-dind
  when: on_success
  only:
    - master
    - /^rl-.*$/
    - dev
    - ft-buildtools-luc

staging:
  stage: deploy
  image: alpine:latest
  script:
    - apk update
    - apk add --no-cache openssh-client sshpass bash
#    - bash
    - chmod +x ./docker/_deploy.sh
    - ./docker/_deploy.sh
  tags:
    - cs108
  when: manual
  environment:
    name: "staging/$CI_COMMIT_SHA"
    url: "$CI_COMMIT_SHA.s01.subluminal.tech"
    on_stop: stop_env
  only:
    - /^rl-.*$/
    - ft-buildtools-luc


# production:
#   stage: deploy
#   image: bash:latest
#   script:
#     - echo "Missing sh script to setup production environment."
#   tags:
#     - cs108-dind
#   when: manual
#   environment:
#     name: production
#   only:
#     - master


pages:
  stage: deploy
  image: bash:latest
  script:
    - mkdir public
    - cp web/docs/index.html public
    - mkdir public/javadoc
    - cp -r docs/javadoc/* public/javadoc
    - mkdir public/test
    - cp -r app/build/reports/test/* public/test
    - mkdir public/coverage
    - cp -r app/build/reports/coverage/* public/coverage
  tags:
    - cs108-dind
  artifacts:
    paths:
    - public
  only:
    - master
    - ft-buildtools-luc

stop_env:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - ./docker/_stop.sh
  when: manual
  environment:
    name: "staging/$CI_COMMIT_SHA"
    action: stop
