image: gradle:4.6.0-jdk8-alpine

before_script:
  - echo "----- Start CI -----"
  - pwd
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - checkstyle
  - test
  - build
  - javadoc

checkstyle:
  stage: checkstyle
  script:
    - gradle check
  tags:
    -cs108
  only:
    - ft-buildtools-luc

test:
  stage: test
  script:
    - gradle test
  tags:
  - cs108

build:
  stage: build
  script:
  - gradle build
  tags:
  - cs108

  javadoc:
    stage: javadoc
    script:
      - gradle check
    tags:
      -cs108

after_script:
  - echo "----- End CI -----"
