image: subluminalthegame/gradle:4.6.0-jdk8-openjfx-alpine

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_OPTS="-Dfile.encoding=utf-8"

cache:
  paths:
    - .gradle/

stages:
  - checkstyle
  - build
  - test
  - coverage
  - javadoc
  - testing
  - staging
  - production

cache:
  paths:
    - .gradle

checkstyle:
  stage: checkstyle
  script:
    - gradle check
  tags:
    - cs108
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out
  only:
    - /^rl-.*$/

build:
  stage: build
  script:
    - gradle clean
    - gradle build -x check -x test
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out

test:
  stage: test
  script:
    - gradle test
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out

coverage:
  stage: coverage
  script:
    - gradle jacocoTestReport
    - cat app/build/reports/coverage/index.html
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out

javadoc:
  stage: javadoc
  script:
    - gradle -q javadoc
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out
  only:
    - /^rl-.*$/

testing:
  stage: staging
  image: docker:latest
  variables:
    DOCKER_DRIVER: 'overlay2'
    VERSION: 'null'
  services:
  - docker:dind
  before_script:
  - docker info
  script:
  - VERSION=$(cat VERSION)
  - echo Building and deploying server verison $VERSION to CI_JOB_NAME
  - docker build -t subluminalthegame/subluminal:latest -t subluminalthegame/subluminal:3.0.0 .
  - docker login -u subluminalthegame -p $DOCKERHUB_PASSWORD
  - docker push subluminalthegame/subluminal
  - apk update
  - apk add --no-cache openssh-client sshpass
  - sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no gitlab@$DEPLOYHOST docker stop subluminal_staging || true
  - sshpass -p $DEPLOY_PASSWORD ssh gitlab@$DEPLOYHOST docker pull subluminalthegame/subluminal:latest
  - sshpass -p $DEPLOY_PASSWORD ssh gitlab@$DEPLOYHOST docker run --rm -d -p 1727:1729/tcp --name subluminal_staging subluminalthegame/subluminal:latest
  tags:
    - cs108
  #when: on_success
  when: manual
  environment:
    name: staging
  only:
    - dev
    - ft-buildtools-luc

staging:
  stage: testing
  script:
    - echo "Missing sh script to setup testing environment."
  tags:
    - cs108
  #when: on_success
  when: manual
  environment:
    name: staging
  only:
    - /^rl-.*$/


production:
  stage: production
  script:
    - echo "Missing sh script to setup production environment."
  tags:
    - cs108
  when: manual
  environment:
    name: production
  only:
    - master
