image: gradle:4.6.0-jdk8

stages:
  - test
  - build
 
before_script:
  - echo "Start CI"
  - pwd
  - gradle --version
  - gradle wrapper

test:
  stage: test
  script:
    - sh ./gradlew test
  tags:
  - cs108

build:
  stage: build
  script:
  - sh ./gradlew build
  tags:
  - cs108

after_script:
  - echo "End CI"