image: subluminalthegame/gradle:4.6.0-jdk8-openjfx-alpine

before_script:
  - echo "----- Start CI -----"
  - pwd
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/

stages:
  - checkstyle
  - build
  - test
  - coverage
  - javadoc
  - staging
  - deploy

cache:
  paths:
    - .gradle

checkstyle:
  stage: checkstyle
  script:
    - gradle check
  tags:
    - cs108
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA	"
    paths:
      - app/build/
      - app/out
  only:
    - /^rl-.*$/

build:java:
  stage: build
  script:
    - gradle build
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - app/build/
      - app/out

test:
  stage: test
  script:
    - gradle test
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out

coverage:java:
  stage: coverage
  script:
    - gradle jacocoTestReport
    - cat app/build/reports/coverage/index.html
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out
  
build:
  stage: build
  script:
    - gradle build -x check -x test
  tags:
    - cs108
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out

javadoc:
  stage: javadoc
  script:
    - gradle -q javadoc
  tags:
    - cs108
  allow_failure: true
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - app/build/
      - app/out
  only:
    - /^rl-.*$/

staging:
  stage: staging
  script:
    - echo "Missing sh script to setup testing/staging environment."
  when: manual
  only:
    - /^rl-.*$/
    - dev

deploy:
  stage: staging
  script:
    - echo "Missing sh script to setup deployment environment."
  when: manual
  only:
    - master

after_script:
  - echo "----- End CI -----"
