image: gradle:4.6.0-jdk8

stages:
  - test
  - build
 
before_script:
  - cd "/home/gradle/project"

test:
  stage: test
  script:
    - ./gradlew test
  tags:
  - cs108

build:
  stage: build
  script:
  - ./gradlew build
  tags:
  - cs108

after_script:
  - echo "End CI"