image: gradle:4.6.0-jdk8

stages:
  - test
  - build
 
before_script:
  - echo "Start CI"
  - pwd

test:
  stage: test
  script:
    - sudo gradle test
  tags:
  - cs108

build:
  stage: build
  script:
  - sudo gradle build
  tags:
  - cs108

after_script:
  - echo "End CI"